FROM node:lts-alpine

# Définir le répertoire de travail dans le conteneur
# WORKDIR /app

# Copier les fichiers nécessaires
# COPY . .

# Installer les dépendances
RUN yarn install

# Exposer le port sur lequel le serveur fonctionnera
# EXPOSE 3000

# Commande pour démarrer le serveur Express Node.js
CMD ["bash"]
