---
sonarqube_image: "sonarqube:10.6-community"
sonarqube_port: "9000"
sonarqube_data_volume: "sonar_data"
sonarqube_bundled_plugins_volume: "sonar_bundled_plugins"
sonarqube_logs_volume: "sonar_logs"
sonarqube_db_url: "jdbc:mysql://localhost:3306/sonar"
sonarqube_db_username: "sonar"
sonarqube_db_password: ""