---
- name: Install required packages for Prometheus
  apt:
    name:
      - wget
      - tar
    state: present
    update_cache: yes

- name: Create Prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
    - /opt/prometheus

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0755'

- name: Extract Prometheus binaries
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt/prometheus"
    remote_src: yes
    creates: "/opt/prometheus/prometheus-2.45.0.linux-amd64"

- name: Move Prometheus binaries to /usr/local/bin
  command: >
    mv /opt/prometheus/prometheus-2.45.0.linux-amd64/{prometheus,promtool} /usr/local/bin/

- name: Move Prometheus configuration files
  command: >
    mv /opt/prometheus/prometheus-2.45.0.linux-amd64/{consoles,console_libraries,prometheus.yml} /etc/prometheus/

- name: Set ownership of Prometheus directories
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    recurse: yes
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Create Prometheus service file
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify:
    - Restart Prometheus

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
