[swarm_managers]
VM4 ansible_host=172.16.237.47 ansible_user=student ansible_password=LtCxF2ND8H0l

[swarm_workers]
VM1 ansible_host=172.16.237.12 ansible_user=student ansible_password=zjM22tymSROP
VM2 ansible_host=172.16.237.21 ansible_user=student ansible_password=RlnneaSQBCaT


[gitlab]
VM3 ansible_host=172.16.237.31 ansible_user=student ansible_password=FkMLvtRrC2o7

[all:vars]
ansible_connection=ssh
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root